// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Dev [FirebaseOptions] for the `focus-local-dev` project.
///
/// TODO: Replace the placeholder values below by running:
///
///   cd app
///   ./update_firebase_config.sh
///
/// after `env/dev.json` has been filled in. The script regenerates this
/// file from the Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDstlCT2_HMWYx9Jy8Gd3QblTKZdX8HbPg',
    appId: '1:122163867410:web:0730f6ab7c7ae9b73a8dcb',
    messagingSenderId: '122163867410',
    projectId: 'focus-local-dev',
    authDomain: 'focus-local-dev.firebaseapp.com',
    storageBucket: 'focus-local-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNxdIiY2FTuVDjogt-tkVxkb0DZxPAx8',
    appId: '1:122163867410:android:7e8d909444010d183a8dcb',
    messagingSenderId: '122163867410',
    projectId: 'focus-local-dev',
    storageBucket: 'focus-local-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqK4plVlZktnmNtiXrFeoZx5Q-PEKi44I',
    appId: '1:122163867410:ios:19f6b0640c19d5403a8dcb',
    messagingSenderId: '122163867410',
    projectId: 'focus-local-dev',
    storageBucket: 'focus-local-dev.firebasestorage.app',
    iosClientId: '122163867410-586l67ekldu8k5mtmv419u5ge3311nbj.apps.googleusercontent.com',
    iosBundleId: 'com.pietroid.focus.dev',
  );
}
