// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKxvTkb7lZMDNHPDR8tmhWEwP6p66xYPQ',
    appId: '1:392630770562:android:1d469b95cc3e61977a0d9b',
    messagingSenderId: '392630770562',
    projectId: 'focus-production',
    storageBucket: 'focus-production.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBljHWQYynq6J6tZuKrWUKEM4VdZUiL-oA',
    appId: '1:392630770562:ios:b7a18a9babfb37977a0d9b',
    messagingSenderId: '392630770562',
    projectId: 'focus-production',
    storageBucket: 'focus-production.firebasestorage.app',
    androidClientId:
        '392630770562-674kfcfn2f1qebj30hib25h9p3hcmcqk.apps.googleusercontent.com',
    iosClientId:
        '392630770562-sm05h5l29140puk6osh709c9uunqt376.apps.googleusercontent.com',
    iosBundleId: 'com.pietroid.focus',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdYymFwwvNditKs8xb_lowbjye5bwrVC8',
    appId: '1:392630770562:web:66d91ba0f58081f57a0d9b',
    messagingSenderId: '392630770562',
    projectId: 'focus-production',
    authDomain: 'focus-production.firebaseapp.com',
    storageBucket: 'focus-production.firebasestorage.app',
  );
}
