name: focus
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.4
  currency_text_input_formatter: ^2.2.6
  drag_and_drop_lists: ^0.4.2
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  go_router: ^14.7.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  objectbox_generator: any
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  background_color_ios: "#001830"
  min_sdk_android: 21 # android min sdk min:16, default 21
