name: focus
description: Focus on what is important
version: 0.4.0
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  app_elements:
    path: packages/app_elements
  app_ui: 
    path: packages/app_ui
  bloc: ^8.1.4
  currency_text_input_formatter: ^2.2.6
  content_repository:
    path: packages/content_repository
  drag_and_drop_lists: ^0.4.2
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  glowy_borders: ^1.0.2
  go_router: ^14.6.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  local_service:
    path: packages/local_service
  objectbox: 4.0.3
  objectbox_flutter_libs: 4.0.3
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  rxdart: ^0.28.0
  timer: 
    path: packages/timer
  things:
    path: packages/things
  timely_repository:
    path: packages/timely_repository
  for_you_repository:
    path: packages/for_you_repository
  equatable: ^2.0.7
  

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  objectbox_generator: any
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  background_color_ios: "#001830"
  min_sdk_android: 21 # android min sdk min:16, default 21
