name: app_elements
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  drag_and_drop_lists: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
