name: Deploy Server

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - '.github/workflows/deploy-server.yml'
      - '.github/workflows/deploy-image.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-image.yml
    with:
      component: backend
    secrets: inherit
